# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-03 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20181202_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title']},
        ),
    ]
