# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20181203_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='photo',
            name='yogum',
            field=models.TextField(blank=True, verbose_name='사진 설명'),
        ),
    ]
