# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20181214_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='floor',
            field=models.CharField(blank=True, max_length=50, verbose_name='해당층/건물층'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, verbose_name='지역명'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세 설명'),
        ),
    ]
