# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_photo_elevator'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='inHome',
            field=models.CharField(blank=True, max_length=10, verbose_name='입주가능일'),
        ),
    ]
