# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_photo_inhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='m',
            field=models.CharField(blank=True, max_length=20, verbose_name='전용/공급면적'),
        ),
    ]
