# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_photo_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='animal',
            field=models.CharField(blank=True, max_length=10, verbose_name='반려동물'),
        ),
    ]
