# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_photo_daechul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='daechul',
            new_name='loan',
        ),
    ]
