# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_auto_20181215_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='balcony',
            field=models.CharField(blank=True, max_length=10, verbose_name='베란다/발코니'),
        ),
    ]
